# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'RNA Systems Biology Lab'
    description: 'RNA Systems Biology Lab at BioISI/Ciências ULisboa. Research lab.'
    twitter: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: |
      © {year} RNA Systems Biology Lab. <br>
       Hosted at the [Faculty of Sciences of the University of Lisbon](https://ciencias.ulisboa.pt/en). [Privacy Policy](https://ciencias.ulisboa.pt/en/privacy-policy-faculty-of-sciences).

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  avatar:
    gravatar: false
    shape: circle
  search:
    provider: wowchemy
  # map:
  #   provider: 'mapnik'
  #   api_key: ''
  #   zoom: 15

# Extensions

extensions:
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa
