name: Website PR Preview on Surge

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_preview:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3

    - name: Install Ruby Dev                     
      run: sudo apt-get install ruby-dev

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'
        extended: true

    - name: Setup base URL env var
      run: |
        export PRNUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") 
        echo BASEURL="https://rnasysbiolab-web-build-preview-pr-"$PRNUMBER".surge.sh/" >> $GITHUB_ENV


    - name: Build                                
      run: hugo --baseURL "${{ env.BASEURL }}"

    - name: Deploy                               
      uses: afc163/surge-preview@main
      id: preview_step
      with:
        surge_token: ${{ secrets.SURGE_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist: public
        failOnError: 'true'
        teardown: true
        build: |
          echo Deploying to surge.sh

    - name: Write comment
      uses: actions-cool/maintain-one-comment@v1.1.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ⚡️ Deploying PR Preview...
            <img src="https://user-images.githubusercontent.com/507615/90240294-8d2abd00-de5b-11ea-8140-4840a0b2d571.gif" width="300" />
            <!-- Sticky Pull Request Comment -->
          body-include: '<!-- Sticky Pull Request Comment -->'

    - name: Show the preview URL
       run: echo "${{ env.BASEURL }}" 


# Retrieved from: https://is.gd/Mgniy0
